[package]
name    = "data-macros"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
darling     = "0.10.2"
proc-macro2 = "1.0.12"
quote       = "1.0.4"
syn         = "1.0.18"
