[package]
name = "gen"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
publish = false

[dependencies]
ansi_term.workspace = true
askama = "0.14.0"
cargo_toml = "0.22.3"
chrono.workspace = true
fehler = "1.0.0"
fs_extra = "1.1.0"
git2 = "0.20.2"
globset.workspace = true
libc.workspace = true
log.workspace = true
pretty_env_logger.workspace = true
regex.workspace = true
serde.workspace = true
serde_yaml = "0.9.34"
snafu.workspace = true
structopt.workspace = true
strum.workspace = true
tempfile.workspace = true
url.workspace = true
